name: Build Flet APK
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Instalamos Flet y luego lo que diga tu requirements.txt
          pip install flet
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build APK
        run: |
          # -y acepta licencias de Android SDK automáticamente
          # --project define el nombre que verás al instalarlo en el celular
          flet build apk main.py --project "Sistema Inventario" -y

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Sistema-Inventario-APK
          path: build/apk/*.apk